create table players (
    date_inserted          TIMESTAMPTZ NOT NULL DEFAULT now(),
    sleeper_id             INTEGER,
    to_year                INTEGER,
    from_year              INTEGER,
    stats_timeframe        TEXT,
    ast                    NUMERIC,
    reb                    NUMERIC,
    pts                    NUMERIC,
    roster_status          TEXT,
    draft_number           INTEGER,
    draft_round            INTEGER,
    draft_year             INTEGER,
    country                TEXT,
    college                TEXT,
    weight                 TEXT,
    height                 TEXT,
    position               TEXT,
    jersey_number          TEXT,
    team_abbreviation      TEXT,
    team_name              TEXT,
    team_city              TEXT,
    is_defunct             BOOLEAN,
    team_slug              TEXT,
    team_id                INTEGER,
    player_slug            TEXT,
    player_first_name      TEXT,
    player_last_name       TEXT,
    person_id              INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS unrecognized_players (
    date_inserted          TIMESTAMPTZ NOT NULL DEFAULT now(),
    sleeper_id             INTEGER NOT NULL,
    to_year                INTEGER,
    from_year              INTEGER,
    stats_timeframe        TEXT,
    ast                    NUMERIC,
    reb                    NUMERIC,
    pts                    NUMERIC,
    roster_status          TEXT,
    draft_number           INTEGER,
    draft_round            INTEGER,
    draft_year             INTEGER,
    country                TEXT,
    college                TEXT,
    weight                 TEXT,
    height                 TEXT,
    position               TEXT,
    jersey_number          TEXT,
    team_abbreviation      TEXT,
    team_name              TEXT,
    team_city              TEXT,
    is_defunct             BOOLEAN,
    team_slug              TEXT,
    team_id                INTEGER,
    player_slug            TEXT,
    player_first_name      TEXT,
    player_last_name       TEXT,
    person_id              INTEGER PRIMARY KEY
);

-- V2: create players and "unrecognized players" tables (run this migration against the 'nba' database)
CREATE INDEX IF NOT EXISTS idx_unrec_sleeper_id ON unrecognized_players (sleeper_id);
CREATE INDEX IF NOT EXISTS idx_players_sleeper_id ON players (sleeper_id);